### ISSUE TITLE
error [install basepkgs][255]

### ISSUE THREAD

**Issue by papajoker** [Chrysostomus/aif-dev#151] opened 2017-04-13 15:29 UTC
with this error : 
>[install basepkgs][255] ==> Creating install root at /mnt --install_base()

I guess the problem actually comes from the branch:
destination Branch (root) different from the branch of the installer : 

in [install_base](https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util-base.sh#L203)() function we call : setup_profiles()

setup_profiles() use `pacman -Sy --noconfirm manjaro-iso-profile` (installer branch) but if my root branch is different we use after [basetrap](https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util-base.sh#L282) and somes packages are not found (Normal because it is another branch)

use only one mirror: https://mirror.netzspielplatz.de/manjaro/packages/

?

**Comment by oberon-manjaro** [comment] 2017-04-13 16:09
Need to think about that... Isn't root branch automatically always the same as installer branch??

**Comment by papajoker** [comment] 2017-04-13 16:20
I had this error for an hour (openrc,stable,  install base), 7..8 tests, and it has just passed without error ??? ...

**Comment by oberon-manjaro** [comment] 2017-04-13 16:49
how did it stop in the end? what did you change?

**Comment by papajoker** [comment] 2017-04-13 16:55
Ok I can finally reproduce :)

Before run manjaro-architect: `sudo pacman-mirrors -gi -b testing`, check only `https://mirror.netzspielplatz.de/manjaro/packages/`

In manjaro-architect, choose rank mirror: stable, check only `https://mirror.netzspielplatz.de/manjaro/packages/`

In install base packages (linux44):

    manjaro-iso-profiles-base-17.0-8  manjaro-iso-profiles-community-17.0-8  manjaro-iso-profiles-official-17.0-8

**not good, in stable a have 17.0.7**

My error 255 is actually in `manjaro-system`  :

```
:: Synchronizing package databases...
 core                                              138,0 KiB   450K/s 00:00 [###########################################] 100%
 extra                                            1781,9 KiB  1357K/s 00:01 [###########################################] 100%
 community                                           4,1 MiB  1243K/s 00:03 [###########################################] 100%
 multilib                                          181,5 KiB   814K/s 00:00 [###########################################] 100%
resolving dependencies...
:: There are 11 providers available for linux>=3.4:
:: Repository core
   1) linux310  2) linux312  3) linux316  4) linux318  5) linux41  6) linux410  7) linux44  8) linux48  9) linux49
:: Repository community
   10) linux-rt-lts-manjaro  11) linux-rt-manjaro

Enter a number (default=1): 
looking for conflicting packages...
:: manjaro-system: requires pcmciautils>=018-5
```
ps: add exit for view this error 255 :     `basestrap ${MOUNTPOINT} $(cat /mnt/.base) 2>$ERR; exit 1  `
**manjaro-system choose 1 by default ?**

If I reuse manjaro-archirect without going back to testing before, then this time no error 255 ! only diff is the branch of begining !?

**Comment by oberon-manjaro** [comment] 2017-04-13 17:16
Hm. interesting! How can we prevent this?

**Comment by papajoker** [comment] 2017-04-14 18:19
ok in utils.sh#rank_mirrors() we make only one `pacman-mirror`
after in utils-base.sh#install_base() we call setup_profiles() and install packages with basestrap without make a pacman -Sy**y** before, so we have the old database (branch) in local 

TODO in rank_mirrors()

    [[  old branch != "$branch" ]] && pacman -Syy

**Comment by oberon-manjaro** [comment] 2017-04-14 18:59
👍

**Comment by papajoker** [comment] 2017-04-20 15:46
commit: 2636b58aac497ca68d5b2b02155d347d02f2f8e5

**Comment by Chrysostomus** [comment] 2017-05-09 11:46
Is this issue solved?

**Comment by dprobinson** [comment] 2017-10-24 15:13
I'm getting this error trying to install the i3 desktop via Architect v9.0.2 (on the current latest available ISO), so I'm guessing it's still not fixed completely.

**Comment by Chrysostomus** [comment] 2017-10-24 15:20
Fzf package is broken, this causes the issue.

**Comment by Chrysostomus** [comment] 2017-10-24 15:22
To work around this, after selecting i3 but before selecting custom packages, edit /mnt/.base and /mnt/.desktop to remove packages that depend on fzf. Bmenu, pacui, pacli and so on.

**Comment by dprobinson** [comment] 2017-10-24 15:40
Amazing, thanks @Chrysostomus

**Comment by hakeemrahman24** [comment] 2017-10-26 01:36
> To
 work around this, after selecting i3 but before selecting custom packages, edit /mnt/.base and /mnt/.desktop to remove packages that depend on fzf. Bmenu, pacui, pacli and so on.
> 

I'm a newbie so please be gentle....how exactly can I do this Sir ???
Because I'm already spending hours trying to intall Manjaro on my Ideapad, still no luck....

Btw ... i3 is the DE selection right?

**Comment by Chrysostomus** [comment] 2017-10-26 04:15
Yes.

Assuming you are on the live iso, go to another terminal with ctrl+alt+f2. Log in, run 

        sudo nano /mnt/.{desktop,base}

You delete lines easily with ctrl+k. Save and exit with ctrl+x. Return to installer with ctrl+alt+f1.

**Comment by Chrysostomus** [comment] 2017-10-26 04:16
If still getting errors, post the pacman output (the error is likely in the end)

**Comment by johanneskopf** [comment] 2017-10-26 23:00
I'm getting this error too, but I want to install the KDE desktop environment.
There the output shows this error: 'error: pptpclient: key "Daniel Isenmann <daniel@archlinux.org>" is disabled :: File /var/cache/pacman/pkg/pptpclient-1.8.0-2-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature))'.
I will try if the suggestions above are working and report back.

EDIT: i removed the "network...pptp" package entry using @Chrysostomus instructions, and the error was gone.

**Comment by Chrysostomus** [comment] 2017-10-27 05:13
Note that this is a workaround, and you should later try to install that package. These are problems on the server side and should be fixed server side. The problem is not in the installer or the user, but in the repos. These kinds of things usually get fixed within a day or two. 

Another thing that you can try is updating pacman keys in the preparation menu, in case the problem is in the user's end (for example, old installation media).

**Closed as completed** 2018-01-04 07:34 UTC

**Comment by Yaksinikos** [comment] 2019-04-04 22:19
Its back since the last update on 4. april 2019.

**Comment by Chrysostomus** [comment] 2019-04-05 04:06
Which profile?

**Comment by Yaksinikos** [comment] 2019-04-05 08:35
Just tried Manjaro Architect Installer v.0.9.22 from the MATE, KDE and BSP ISOs.
It fails even on installing basic CLI.
In VM as well as on real hardware.

I did not look up for profiles, but just using the standard architect installer.

I'm talking about the Error 255 in first line.

**Comment by vv0r** [comment] 2019-07-09 17:41
Problem persists stil in some form on bspwm. The minimal packages install fine but if I try the full install it throws the255 error to my face.

**Comment by Chrysostomus** [comment] 2019-07-09 17:51
Thank you for reporting. I'll look into it.

**Comment by LunarLambda** [comment] 2021-03-05 14:08
Getting this error trying to install xfce-minimal

**Comment by n0rbed** [comment] 2021-03-26 18:26
also is an issue here, manjaro bspwm.
