### ISSUE TITLE
We have a structural problem

### ISSUE THREAD

**Issue by Huluti** [Chrysostomus/aif-dev#74] opened 2017-02-28 09:38 UTC
Hi!

I think that we have a problem with the structure of the project. The whole structure is based on the principle of recursion. @papajoker has tried to show it in this comment: https://github.com/Chrysostomus/manjaro-architect/issues/71#issuecomment-282832254.

Here the track of the program it obtains when logging:

> 02/22/17 18:28:15 [rank mirrors][1] --configure_mirrorlist()<-configure_mirrorlist()<-install_base_menu()<-main_menu_online()<-check_base()<-main_menu_online()<-check_base()<-main_menu_online()<-prep_menu()<-main_menu_online()<-check_base()<-main_menu_online()<-prep_menu()<-prep_menu()<-lvm_create()<-lvm_menu()<-prep_menu()<-luks_menu()<-luks_open()<-luks_menu()<-prep_menu()<-mount_partitions()<-prep_menu()<-select_device()<-prep_menu()<-main_menu_online()<-main()]

When you can make loops, you redo calls to the function. In the program for example it is very true for the menus. The path taken by the program is far too complex.

I do not have a good enough level to help you code, but only at the algorithmic level I think there is way to improve the structure.

Tell me if I miss something.

Thank's!

**Comment by Chrysostomus** [comment] 2017-02-28 09:41
What kind of structural problem? Code, layout, organization or something else?

**Comment by Huluti** [comment] 2017-02-28 09:42
I've made a mistake, I have pressed enter without typing my message, just wait a few minutes... :)

**Comment by oberon-manjaro** [comment] 2017-02-28 10:07
I think I see what you mean. The infinite loop of **main_menu_online()**, right?
Maybe it wouldn't even need much change to transform the progress through the available steps in a linear way? ...

**Comment by oberon-manjaro** [comment] 2017-02-28 10:38
Or maybe we just need some places where we exit and cleanly re-enter the loop?

**Comment by oberon-manjaro** [comment] 2017-02-28 10:41
all-in-all it does work well the way it is, I thought... :stuck_out_tongue_winking_eye:

**Comment by Chrysostomus** [comment] 2017-02-28 10:46
@Huluti what kind of structure would you suggest instead?

**Comment by oberon-manjaro** [comment] 2017-02-28 10:48
At the moment we have ``main_menu_online`` running as an infinite loop and on top of that, some menu entries **and** our ``check_for_error`` function invoking it with every exit on error core ...

**Comment by papajoker** [comment] 2017-02-28 13:10
> main_menu_online running as an infinite loop 

Precisely NO, aif have no loop
In all the coding schools, all language, we are told that we must not use a recursive structure as aif

a normal menu (as bmenu,pacli ...) is 

```
function menu(){
    while ((wantexit==0)); do 
        choice= dialog ...
        case choice in
            2: submenuOne
            3: submenu...
            1 : wantexit=1 # exit the loop, the function, return in loop menu parent
        esac
    done
    checks # here a can make code when we exit
}
```

with aif we have not loop :  

```
function menu(){
    choice= dialog
    case choice in
        2: submenu
        3: submenu...
        *: menuParent
    esac
    menu  # recursive : you call in fonction in himself !!!!!!!!
    #checks # here a cant make code when we exit
}
```

and not only with menus, in fonctions as check_for_error and [other](https://github.com/Chrysostomus/manjaro-architect/blob/master/lib/util-base.sh#L115) : we are in a menu fonction and we call the same function menu in. 

we "never" exit a function but we call parent function ! (view my log with calls path)
a normal "calls path" for all programs is

```
main()->mainmenu()->submenu()->mountPartitions()
main()->mainmenu()->submenu()
main()->mainmenu()->submenu()->installbase()
main()->mainmenu()->submenu()
main()->mainmenu()
main()->mainmenu()->submenu2()
main()->mainmenu()->submenu2()->installDesktop()

```
Its all base structure of aif :(

somes problems :  

- memory/variable, not exit function = not free local vars, recreate,stack in each function local vars
- when we exit we not exit from mainmenu() by from stack 200 functions
- code at end of a function is never call or is call 50 times if exit ?
- hard to understand structure for developers

**Comment by oberon-manjaro** [comment] 2017-02-28 13:54
> with aif we have not loop :

What about:
```
while true; do
    main_menu_online
done
```
in [bin/manjaro-architect.in](https://github.com/Chrysostomus/manjaro-architect/blob/master/bin/manjaro-architect.in#L31) ?

**Comment by oberon-manjaro** [comment] 2017-02-28 14:03
And the recursive structure you mention happens **inside** the main_menu loop ... ...

**Comment by papajoker** [comment] 2017-02-28 14:10
:) 
```
while true; do
    main_menu_online
done
```
is a no sens because main_menu_online is recursive !
you have this loop only since 15 days ? you can comment while

when we call main_menu_online() this function call main_menu_online() , its a infinite way , always the only soluce for close this call is `exit` 

----
If I appealed to Huluti, it is that it is extremely difficult for me with my bad English to make you understand. Perhaps with a search on the web as [this](https://en.wikipedia.org/wiki/Recursion_(computer_science)) ?

**Comment by Chrysostomus** [comment] 2017-02-28 14:25
I think I have understood the problem, but it's gonna take a while for me to figure out how to fix it. But it is a issue we need to solve. We have already opened separately two different issues that are caused by this. 

Have I understood correctly, that the proper way to implement this would be to exit functions instead of calling parent functions? That would make more sense to me

**Comment by oberon-manjaro** [comment] 2017-02-28 14:38
> you have this loop only since 15 days ?

no. it was always there!
https://github.com/CarlDuff/aif-dev/blob/master/aif#L2826 :wink:

**Comment by oberon-manjaro** [comment] 2017-02-28 15:00
Looking at pacli right now. It's quite logical. But yes, can you explain how submenus can be integrated into this?

**Comment by oberon-manjaro** [comment] 2017-02-28 15:20
something like ?
```
# main menu
while true; do
    dialog ... "1" "submenu a" "2" "submenu b" "3" "submenu c" "0" "Done" 2>$ANSWER
    case $(cat $ANSWER) in
        "1") a
            ;;
        "2") b
            ;;
        "3") c
            ;;
        "0") final_check
    esac
done

function a() {
    dialog ... "1" "x" "2" "y" "3" "return to main menu" 2>$ANSWER
        case $(cat $ANSWER) in
            ...
            "3") ??? up one level how ?
}

...

final_check() {
    do last things
    exit 0
}
```

**Comment by Chrysostomus** [comment] 2017-02-28 15:27
Bmenu just calls different scripts as submenus. But maybe we just
1) remove calls to menu() from the functions themselves
2) for each submenu and main_menu, add wrapper function  similar to 
```
while true; do
    main_menu_online
done
```
3) cancel/done actions exit wrapper loops

**Comment by papajoker** [comment] 2017-02-28 15:28
Warning
Changing the structure of aif is a huge job that takes a lot of time and does not bring anything to the program user.
- it is necessary to create another branch
- everything in the master branch is frozen

Take time for reflection

**Comment by Chrysostomus** [comment] 2017-02-28 15:29
yep, its huge undertaking, and only solves minor issues for end user. I still suggest we do it, lets wrap some other things first

**Comment by oberon-manjaro** [comment] 2017-02-28 15:40
Yes, lets start that project don a new branch but focus on ironing out the issue on what we have.
It would just be good that we don't create more stuff that we have to do completely differently again later.

**Comment by oberon-manjaro** [comment] 2017-02-28 15:45
I would just like to understand the one thing I tried to ask above:
Is it an option at all to have submenu-loops inside the main-menu-loop and if yes, how does one step up a level out of the inner loop?
Or can we have only one loop and the submenus inside need to be linear functions?

**Comment by Chrysostomus** [comment] 2017-02-28 15:58
I think we can have submenu loops within the main menu loop as long we exit the submenu and dont call new main menu instance from within submenu.

**Comment by oberon-manjaro** [comment] 2017-02-28 16:09
So exit just with ``break`` you mean?

**Comment by oberon-manjaro** [comment] 2017-02-28 16:13
The other question, maybe more important right now, is: If the recursive structure is in fact responsible for some issues, how can we repair that for now?

**Comment by papajoker** [comment] 2017-02-28 16:23
sorry but recursive is so bad that it is impossible for me to understand if is the coupable

-----------------
a litte script for play/test with good structure (only for menus)

```
#!/usr/bin/bash
ANSWER='./tmp'

subMenu()
{
    declare -i loopmenu=1
    while ((loopmenu)); do
        dialog --title  " submenu " --menu "sub" 0 0 9 \
        "1" "format" \
        "2" "install" \
        "3" "done" 2>${ANSWER}
        if (($?==0)); then
            case "$(<${ANSWER})" in
                1) format__
                    ;;
                2) install__
                    ;;
                3) return  99 # (exemple) exit without run end of this function
                    ;;             
            esac
        else
            # btn cancel
            loopmenu=0
        fi
    done
    # if you want
    # check_exit_this_sub_menu
    [ -f "${ANSWER}" ] && rm "${ANSWER}" # exemple not util
    # return to parent function
}

mainMenu()
{
    declare -i loopmenu=1
    while ((loopmenu)); do
        dialog --title  " main " --menu "main" 0 0 9 \
        "1" "submenu         >" \
        "2" "..." \
        "3" "futur" \
        "4" "nothing" 2>${ANSWER}
        if (($?==0)); then
            case "$(<${ANSWER})" in
                1) subMenu
                    ;;
                2) :
                    ;;
                *) : #error 
                    ;; 
            esac
        else
            # btn cancel
            loopmenu=0
        fi
    done
    # if you want
    # check_exit_menu
    [ -f "${ANSWER}" ] && rm "${ANSWER}"   # exemple not util
    # return to parent function
}



mainMenu
```
for exit from loop, 2 differents choices
- loopmenu=0  # exec end 
- return   # not exec end, for exemple if error not run check

**Comment by oberon-manjaro** [comment] 2017-02-28 19:59
@papajoker , is $loopmenu a local var? Or does it apply for all (sub)menus at the same time?

**Comment by papajoker** [comment] 2017-02-28 20:28
i use : `declare -i loopmenu=1` (in a function), declare is as `local` so different vars in each menu/sub-menu
and i have more options with [declare](http://wiki.bash-hackers.org/commands/builtin/declare?s[]=declare) as for exemple
- `-i` is a interger
-  `-r` is read only
-  `-g` is global

for constants, declare is best : `declare -r ERR='/tmp/errors'`

---
When writing a program, it is recommended to use conventions of variable naming (father of the program that decides)
for example
- constant: uppercase ERR # old conventions, now only var in ENV are uppercase
- translated: string _var
- local var: __var # one exemple ;)

This greatly simplifies the code reading

**Comment by Chrysostomus** [comment] 2017-03-01 03:57
I suggest the following:
1) fix the most outstanding bugs (unmounting, git cloning, etc) 
2) start transition to better structure in development branch and freeze the master for the time being. 

I think we are in a good place featurewise right now. I don't think we need to add new features anymore for the time being. When we fix these issues, I think the installer is ready for stable.

**Comment by oberon-manjaro** [comment] 2017-03-01 04:33
In fact, I am almost done with a new non-recursive version of the installer on my fork. The necessary changes were not overwhelmingly big and I didn't need to touch any of the features themselves. It's just the outside structure that has changed.
Have a look here @Chrysostomus @papajoker @Huluti 
https://github.com/oberon2007/manjaro-architect
I have two or three things still to fix, then I will provide a **manjaro-architect-exp** package and we can decide after a few test-runs if maybe we want to switch now in fact.
The fork has feature parity although I'm afraid it may be difficult to merge for conflicts.

**Comment by oberon-manjaro** [comment] 2017-03-01 04:38
I will just open a PR in any case - like that it will be better to compare.

**Comment by Chrysostomus** [comment] 2017-03-01 04:38
Okay, I'll refrain from committing changes for the moment then.

**Comment by oberon-manjaro** [comment] 2017-03-01 04:55
you can do and I will just adopt them on my fork.

**Comment by oberon-manjaro** [comment] 2017-03-01 10:42
I agree it is a good idea to freeze code now very soon.
We don't need to switch to the new sttructure immediately it just seems like a good idea to have one repo to concentrate on and it would be cool of course if further development would be already with the code that we are going to use in the future. Especially as soon as it comes to menu logistics and such we need to introduce changes in whatever structure will be the future form.
Some issues even might become obvious with the new version that were possibly not apparent in the old form. So I think in any case it will be good to test the new one also in regards of that and of course we should wait what @papajoker and @Huluti have to say about my proposed form - maybe it isn't better than what we have, anyway :stuck_out_tongue_winking_eye:

**Comment by Chrysostomus** [comment] 2017-03-01 11:10
Testing the manjaro-architect-exp, it seems to have the same issues with exiting.

**Comment by papajoker** [comment] 2017-03-01 12:08
It is always recursive
- the rule never call a parent function
- only the parent menu calls a submenu, submenu never call parent
- no job function calls a menu, its a parent ;) , it returns (a errcode that the parent function interprets)
---

only way for control is to add Temporarily the "heap calls" in logs

     "${FUNCNAME[*]}"

if repeat function = recursive call :(

------

for check_for_error
i suppose that the new structre is

       if [[  "${_function_menu}" != "SKIP" ]]; then
            DIALOG " $_ErrTitle " --msgbox "\n${_msg}\n" 0 0
            return ${_err}
       fi

and in parent (i suppose, not tested) : 

      check_for_erreur "title" $? || return 99

 if we have an error, we exit the job function for the parent (menu or not), if parent not a menu it evaluate the code returned and call "return"

**Comment by Chrysostomus** [comment] 2017-03-04 13:45
I think this is now solved

**Closed as completed by Chrysostomus** 2017-03-04 13:45 UTC

**Comment by Huluti** [comment] 2017-03-06 19:26
Very good work guys! I'm sorry, I didn't have much time theses days and I couldn't help you more .. Congratulations in any case.

**Comment by oberon-manjaro** [comment] 2017-03-07 12:51
Thank you, @Huluti ! :smile: For me this was a huge learning experience and I am extremely thankful for it. With @papajoker we had great expert support.
