### ISSUE TITLE
Creating lvm on encrypted root returns an error

### ISSUE THREAD

**Issue by Onfroygmx** [Chrysostomus/aif-dev#168] opened 2017-05-20 09:23 UTC
I tried to create an lvm partition in an encrypted root:
https://cloud.githubusercontent.com/assets/25054585/26274637/55c943e2-3d4e-11e7-940a-5cd2713c5135.png
https://cloud.githubusercontent.com/assets/25054585/26274640/5dbfcc42-3d4e-11e7-8671-a20f5c912764.png

returns 

https://cloud.githubusercontent.com/assets/25054585/26274643/6ab94fe0-3d4e-11e7-8ae7-d107ff34c2c6.png

Here is the code related
# Convert the VG size into GB and MB. These variables are used to keep tabs on space available and remaining
[[ ${VG_SIZE_TYPE:0:1} == "G" ]] && LVM_VG_MB=$(( VG_SIZE * 1000 )) || LVM_VG_MB=$VG_SIZE

And then I'm kicked out of the installer, nothing is logged in m-a.log

**Comment by Onfroygmx** [comment] 2017-05-20 19:32
There is really something wrong with lvm creation module:

https://cloud.githubusercontent.com/assets/25054585/26278788/4311f1e0-3da3-11e7-913a-cee14482fcfa.png
https://cloud.githubusercontent.com/assets/25054585/26278793/5e932a38-3da3-11e7-89d2-7c067689c6b6.png
https://cloud.githubusercontent.com/assets/25054585/26278795/75251662-3da3-11e7-80de-2c0af99bbff1.png
https://cloud.githubusercontent.com/assets/25054585/26278800/a2a3e44c-3da3-11e7-8913-90909863aea1.png
https://cloud.githubusercontent.com/assets/25054585/26278805/b86ca9a8-3da3-11e7-87c7-67cf67e82489.png

**Comment by Chrysostomus** [comment] 2017-05-20 19:43
Seems pretty messed up. Might be more than one thing wrong with it. I confess I haven't tested the lvm module at all - or lvm in general for that matter. We got it as legacy from the original architect installer, and it might have taken some damage when we transitioned to non-recursive menu structure. Need to look into this. 

Can you test if lvm works with original architect?

**Comment by oberon-manjaro** [comment] 2017-05-20 22:12
Seems to be a regression. This used to work. dot and I tested it quite extensively.
See from https://forum.manjaro.org/t/installation-with-manjaro-architect-iso/20429/85
and further down in the thread...

**Comment by oberon-manjaro** [comment] 2017-05-20 22:27
Also in combination with LUKS [here](https://forum.manjaro.org/t/problems-with-luks-lvm-installation-with-manjaro-architect/20778) - there was of course the problem with crypttab and fstab creation, but LVM creation was always working fine for me.

**Comment by Onfroygmx** [comment] 2017-05-21 08:34
I tried with an empty VB to see if it could be my setup that generates the error, but I have the same errors message as in the first post on following line:
[[ ${VG_SIZE_TYPE:0:1} == "G" ]] && LVM_VG_MB=$(( VG_SIZE * 1000 )) || LVM_VG_MB=$VG_SIZE

If I do it manually, the first step is to create a physical volume:
pvcreate DEVICE
This option is not present in M-A, the first step is to create the VG can this be the cause?

Steps to reproduce:
Start M-A
>prepare installation
>>partition disk (2 partitions: EFI, linux file system)
>>Logical Volume Management
>>> Create VG and LV
>>>> Whatever I enter returns the error.

**Comment by Onfroygmx** [comment] 2017-05-21 15:18
Original Architect installer does not pass the first screen anymore. They also need some iso updates so now and then.

**Comment by Chrysostomus** [comment] 2017-05-21 15:24
I checked the original code. It does not pass pvcreate either. It seems we need to rework the function.

**Comment by Onfroygmx** [comment] 2017-05-21 19:42
Seems the error logging was removed for vg creation
https://github.com/Chrysostomus/manjaro-architect/commit/fd34260e6c0146cd371a6d25078b855cca8f4924

line ±630:
vgcreate -f ${LVM_VG} ${VG_PARTS} >/dev/null 2>$ERR
to
 vgcreate -f ${LVM_VG} ${VG_PARTS} >/dev/null

**Comment by Onfroygmx** [comment] 2017-05-22 12:20
Ok I think I found the culprit.
First:
When you do a vgcreate, you do an implicit pvcreate so this is indeed not mandatory.
Second:
The issue is actually with the retrieval of information from vgdisplay (not sure if this is a regression of lvm2 or linked to the locale being used during the setup).

```
Output of vgdisplay (removed unnecessary parts):
test1
  --- Volume group ---
  VG Name               vglvmluks
  System ID             
  Format                lvm2
  VG Size               <7.50 GiB
test2
  --- Volume group ---
  VG Name               lvmluks
  System ID             
  Format                lvm2
  VG Size               <14.88 GiB
  PE Size               4.00 MiB

Past
  --- Volume group ---
  VG Name               fileserver
  System ID
  Format                lvm2
  VG Size               93.14 GB

Variable VG size line 662:
VG_SIZE=$(vgdisplay $LVM_VG | grep 'VG Size' | awk '{print $3}' | sed 's/\..*//; s/\,.*//')

returns
<7 => should be 7.50
<14 => should be 14.88
93 => is with the old architect installer 93.14

provoking errors ([[ ${VG_SIZE_TYPE:0:1} == "G" ]] && LVM_VG_MB=$(( VG_SIZE * 1000 )) || LVM_VG_MB=$VG_SIZE):
util-disk.sh line 668: <7: syntax error: operand expected (error token is "<7")
util-disk.sh line 668: <14: syntax error: operand expected (error token is "<14”)
```

The solution would be to change the sed function to retrieve the numbers only.

**Comment by Chrysostomus** [comment] 2017-05-22 12:23
Thank you, that saves me several hours of research and reading!

**Comment by Chrysostomus** [comment] 2017-05-22 12:59
This should work better...

VG_SIZE=$(vgdisplay $LVM_VG | awk '/VG Size/ {print $3}' | sed -e 's/<//')

**Comment by Chrysostomus** [comment] 2017-05-22 13:01
Fix committed.

**Comment by Onfroygmx** [comment] 2017-05-22 13:37
Almost!
util-disk.sh line 668: 7.50: syntax error: invalid arithmetic operator (error token is ".50")
and
util-disk.sh line 668: 7.00: syntax error: invalid arithmetic operator (error token is ".00")

Did something ugly, but it works, sure a command line guru can optimize that.
VG_SIZE=$(vgdisplay $LVM_VG | awk '/VG Size/ {print $3}' | sed -e 's/<//' | sed 's/\..*//; s/\,.*//')

sda                8:0    0     8G  0 disk 
├─sda1             8:1    0   512M  0 part /mnt/boot
└─sda2             8:2    0     7G  0 part 
  └─testlvm-lvol 254:0    0     7G  0 lvm  /mnt

**Comment by Chrysostomus** [comment] 2017-05-22 13:43
It does not work reliably, test2 ouput gives 

    .88
when filtered with that sed

**Comment by Chrysostomus** [comment] 2017-05-22 13:46
Committed now a potential fix.

**Comment by Onfroygmx** [comment] 2017-05-22 13:54
The backslash was remove/interpreted by github but it was in my command.

**Comment by Chrysostomus** [comment] 2017-05-22 21:57
Testing this now. Not working yet...

**Comment by Chrysostomus** [comment] 2017-05-22 22:06
Everything seems to be fine until the function gets to run lvcreate:

![screenshot from 2017-05-23 01-03-29](https://cloud.githubusercontent.com/assets/12002226/26330306/f276acfa-3f53-11e7-93c1-c420ceb4e320.png)


Full error output of that command is:

```
  /dev/mapper/control: open failed: No such device
  Failure to communicate with kernel device-mapper driver.
  Check that device-mapper is available in the kernel.
  Incompatible libdevmapper 1.02.140 (2017-05-03) and kernel driver (unknown version).
  striped: Required device-mapper target(s) not detected in your kernel.
  Run `lvcreate --help' for more information.

```

Trying to load the appropriate kernel module seems to fail:
```

sudo modprobe dm_mod                                                                
modprobe: FATAL: Module dm_mod not found in directory /lib/modules/4.10.16-1-MANJARO
```

EDIT: Okay, after reboot it seems to just work...

**Comment by Onfroygmx** [comment] 2017-05-23 07:34
I only played with the one installed on the iso: 4.9.2X
And did not receive the error.

**Comment by Chrysostomus** [comment] 2017-06-02 16:46
Does the issue still happen?

**Closed as completed** 2018-01-03 22:30 UTC
